### PR TITLE
Removing meteorkitchen

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @Urigo 

removing a dead link to meteorkitchen.

Cheers!

### CODE REVIEW

**Comment by Urigo** [comment]
it works, it just didn't update the SSL certificate

**Comment by spekulatius** [comment]
hmm, yeah, that means it isn't accessible (unless you actively allow it).

**Comment by peernohell** [comment]
I just checked and the link work perfectly. they certainly fixed their SSL issue.
I think this PR can be removed.

**Comment by StorytellerCZ** [comment]
Just need to change it to `https`

**Comment by spekulatius** [comment]
It redirects too. Let's close it.

**Pull request closed without merging**
