### PR TITLE
Update resources section

### PR DESCRIPTION
**Pull request by harryadel**
This list used to act as reference to all Meteor stuff regardless of their recency and current value compared to the state of Meteor, prime example being the old and deprecated Meteor tutorials, but It's important to keep this list up to date as much as possible since lots of new comers rely on it to guide them on their Meteor journey. Old stuff would be still kept if it still holds some value.

- Removed all the 1.x resources since they're longer viable but kept leveluptutorials with a little note.
- Added new Social and Work opportunities sections.
- Added a new reference for [Packosphere](https://packosphere.com/).

### CODE REVIEW

**Comment by harryadel** [comment]
@Urigo

**Review by StorytellerCZ — APPROVED** [review]

**Comment by Urigo** [comment]
Thank you so much @harryadel !

About removing the old stuff, maybe some people would still find it useful, how about adding a section at the very bottom for old stuff, just to keep them (I think skim through them every couple of months to take cool old ideas from there.....)

**Comment by harryadel** [comment]
Apologies for the delayed response. Good idea, I went ahead and created deprecated section so we slowly populate it later on.

**Review by StorytellerCZ — APPROVED** [review]

**Comment by Urigo** [comment]
thank you, this is awesome!

**Pull request merged**
