### PR TITLE
Added uniforms.

### PR DESCRIPTION
**Pull request by radekmie**
It's not a Meteor-specific package, but developed for it and integrated with it out of the box - both SimpleSchema versions. Kind of `aldeed:autoform` in React.

### CODE REVIEW

**Comment by Urigo** [comment]
@radekmie that's really cool!
could you maybe add in the description of the link the integration it has with SimpleSchema and link to the section in the docs about that as well?

**Comment by radekmie** [comment]
Like this?

> Bunch of React components and helpers to easily generate and validate forms. [Seamlessly integrate with `aldeed:simple-schema` and `simpl-schema`](https://github.com/vazco/uniforms/blob/master/INTRODUCTION.md#quick-start).

**Comment by Urigo** [comment]
yes perfect

**Comment by Urigo** [comment]
thanks @radekmie

**Pull request merged**
