### PR TITLE
Orion CMS + fix on CONTRIBUTE.md

### PR DESCRIPTION
**Pull request by PEM--**

### CODE REVIEW

**Comment by PEM--** [comment]
Far better. In the meantime, I've also updated the `CONTRIBUTE.md` as the `make server` target doesn't exist and it seems that you relies on `Gulp`.

**Comment by gillesfabio** [comment]
Thanks! Please, could you replace the `gulp` command by `make serve` in CONTRIBUTE.md (see [Makefile](https://github.com/gillesfabio/awesome-meteor/blob/master/Makefile#L11))? And could you also update [the date](https://github.com/gillesfabio/awesome-meteor/pull/19/files#diff-2c55ce16abe408b3d522a9166ea5f359R1033)? Thank you!

**Comment by PEM--** [comment]
Done :smile:

**Comment by gillesfabio** [comment]
Thank you @PEM--!

**Comment by PEM--** [comment]
My pleasure. Pretty nice list by the way. Thank you for sharing it.

**Pull request merged**
